apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  rhtap/gitops: codegen-010304
  janus-idp.io/tekton: codegen-010304
  backstage.io/kubernetes-id: codegen-010304
  backstage.io/kubernetes-namespace: rhdh-app
  app.kubernetes.io/part-of: codegen-010304
resources:
- application-dev.yaml
- gitops-repository.yaml
- source-repository.yaml
- initialize-namespace.yaml
