apiVersion: batch/v1
kind: Job
metadata:
  name: dsp-clone-job-codegen-010304-gitops
spec:
  template:
    metadata:
      name: dsp-clone-job-codegen-010304-gitops
    spec:
      serviceAccountName: codegen-010304-dsp-job
      containers:
        - name: initialize-dsp
          image: quay.io/redhat-ai-dev/utils:latest
          command:
            - /bin/bash
            - -c
            - |
              NS=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)
              oc wait -l statefulset=codegen-010304-notebook --for=condition=ready pod --timeout=300s
              oc exec  StatefulSet/codegen-010304-notebook -- git clone https://github.com/fpetk/codegen-010304
      restartPolicy: Never
